---
## Author
author:
  name: Ермолаев Алексей Максимович
  degrees: бакалавр
  orcid: нет
  email: vashermoalevalexey@gmail.com
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117228
      city: Москва
      address: ул. Пушкина, д. Колотушкина

## Title
title: "Доклад на тему 'Двухфакторная аутентификация'"
subtitle: "по дисциплине 'Математические основы защиты информации и информационной безопасности'"
license: "CC BY"
---

# Цель работы

Познакомиться с основными аспектами двухфакторной аутентификации.

# Теоретическое введение

В век повсеместной цифровизации становится невозможным спорить со статистическими фактами о безопасности использования сетевых ресурсов:

* По данным облачной платформы для управления идентификацией и доступом JumpCloud, в 2024 году количество утечек паролей достигло рекордных 10 млрд записей [@jumpcloud2023].

* Каждые 39 секунд происходит попытка взлома методом перебора паролей [@astra2024], а 81% подтверждённых взломов связан со слабыми или украденными учётными данными [@varonis2024].

* Исследование Stanford University показало, что 88% киберинцидентов включают человеческий фактор: сотрудники используют слабые пароли, переиспользуют их на разных сервисах или становятся жертвами фишинга [@knowbe42023].

* 60% компаний имеют более 500 учётных записей с бессрочными паролями [@packetlabs2024].

* Среднее время до клика по фишинговой ссылке составляет всего 21 секунду, а до ввода учётных данных — 28 секунд [@verizon2024].

В этих условиях комплексный вариант аутентификации становится критически важным барьером между злоумышленниками и личными данными, для чего используется так называемая двухфакторная аутентификация.

# Определение в рамках стандарта NIST SP 800‑63B

Двухфакторная аутентификация (2FA) — это метод подтверждения личности пользователя с использованием двух независимых факторов из разных категорий.

Согласно стандарту NIST SP 800‑63B [@nist2017], для достижения уровня аутентификации AAL2 (Authenticator Assurance Level 2 – уровень, подразумевающий использование двух независимых факторов аутентификации, подтверждающих личность пользователя) требуется доказательство владения и контроля двух различных факторов аутентификации:

* *Фактор знания*: Информация, которой Вы знаете - пароли, PIN‑коды и кодовые фразы. Это наиболее распространённый, но и самый уязвимый тип аутентификации. Пароли могут перехватить через фишинг, украсть с помощью кейлоггеров – программа, фиксирующая нажатие клавиш - или подобрать методом перебора. К тому же, на основе стандарта NIST не рекомендуется использовать контрольные вопросы ввиду их идентичности.

* *Фактор владения*: Устройства, которыми Вы располагаете - физические и виртуальные объекты: аппаратные токены, программные токены в мобильных приложениях и смарт‑карты. К этой категории также относятся современные устройства, оснащённые специализированными аппаратными модулями.

* *Фактор принадлежности*: Ваши биометрические характеристики - отпечатки пальцев, распознавание лица с 3D‑структурированным светом, сканирование радужной оболочки глаза, анализ голоса. Современные системы включают поведенческую биометрию — анализ динамики набора текста или походки.

Дополнительно можно выделить *факторы местоположения* и *временные факторы*, но они специфичны для конкретных условий авторизации.

# Виды решений для 2FA

Есть разные виды решений для 2FA, но мы рассмотрим основные и отранжируем их по степени надежности.

# Push-уведомления

Push-уведомления - относительно новый метод двухфакторной аутентификации. Уведомления отправляются непосредственно на устройство пользователя через специальное приложение [@aws2024].

Типичный сценарий использования push-уведомлений таков - после ввода логина и пароля пользователь получает мгновенное уведомление на смартфон или планшет с просьбой подтвердить или отклонить попытку входа одним касанием. Такой подход не требует вручную вводить коды и значительно ускоряет процесс авторизации.

|Плюсы|Минусы|
|-----|------|
|**Простота использования**: Достаточно нажать «Подтвердить»  в полученном уведомлении, без необходимости копировать или вводить коды. |**Требуется интернет**: Без доступа к интернету push-уведомления не будут доставлены.|
|**Повышенная безопасность**: Push-уведомления сложнее перехватить по сравнению с СМС, они проходят по зашифрованным каналам. |**Ограниченное распространение**: Не все сервисы поддерживают аутентификацию через push-уведомления.|
|**Информативность**: Уведомления могут содержать детали о попытке входа (локация, устройство), помогая выявить несанкционированный доступ.|**Зависимость от устройства**: Как и с другими мобильными методами, потеря телефона может привести к проблемам с доступом.|
|**Нет затрат на СМС**: Экономия на сообщениях при использовании за границей или при большом количестве входов.|**Уязвимость для потенциального мошенничества**:  Пользователи могут машинально подтверждать уведомления, не вчитываясь в их содержание.|

: Преимущества и недостатки push-уведомлений {#tbl-pros-cons-push}

# Приложения-аутентификаторы

Следующий по надежности метод двухфакторной аутентификации — специальные приложения, такие как Google Authenticator, Microsoft Authenticator и Mulifactor. 

Данные приложения привязываются к аккаунту пользователя при первой настройке и после этого генерируют временные коды, которые обновляются интервально (как правило, каждые 30–60 секунд). Для авторизации необходимо ввести код, сгенерированный таким приложением, в нужный сервис [@kaspersky2022].

|Плюсы|Минусы|
|-----|------|
|**Повышенная безопасность**: В отличие от СМС, коды генерируются локально на устройстве и недоступны для перехвата через телефонную сеть.|**Зависимость от устройства**: Потеря смартфона с аутентификатором приведет к потере доступа к защищенным аккаунтам, если не настроены резервные методы восстановления.|
|**Работа в офлайн-режиме**: Для получения кода не требуется подключение к интернету или сотовой сети — приложение работает даже в авиарежиме.|**Необходимость установки**: Требуется скачать и настроить отдельное приложение, а это  дополнительный барьер для неопытных пользователей.|
|**Удобство и скорость**: Коды доступны мгновенно, не нужно ждать СМС.|**Сложности при смене устройства**: Перенос аккаунтов между устройствами требует дополнительных действий, особенно для простых аутентификаторов вроде Google Authenticator.|
|**Мультиплатформенность**: Некоторые аутентификаторы позволяют синхронизировать аккаунты на нескольких устройствах. Это удобно при использовании разных гаджетов.|**Ограниченная совместимость**: Не все сервисы поддерживают аутентификаторы, хотя это встречается все реже.|

: Преимущества и недостатки приложений-аутентификаторов {#tbl-pros-cons-auth}

# Аппаратные ключи безопасности

Следующий метод аутентификации, считающийся одним из самых защищенных – использование аппаратных ключей, такие как Рутокен, YubiKey. Аппаратные ключи — это физические устройства, которые подключаются к компьютеру или смартфону через USB, NFC или Bluetooth. 

При входе в аккаунт пользователь вставляет или прикладывает к устройству ключ, который генерирует уникальный зашифрованный код, невидимый для пользователя и недоступный злоумышленникам [@yubico2024].

|Плюсы|Минусы|
|-----|------|
|**Высокий уровень защиты**: Физические ключи практически невозможно взломать удаленно — для аутентификации требуется физическое наличие устройства.|**Стоимость**: Качественные физические ключи стоят дорого.|
|**Защита от фишинга**: Даже если пользователь попал на поддельный сайт, злоумышленники не смогут получить доступ к аккаунту, так как ключ взаимодействует только с подлинными URL.|**Риск потери**: Во-первых, отсутствие ключа можно не сразу заметить. А во-вторых, потеря может привести к блокировке доступа к аккаунтам, если не настроены альтернативные методы входа.|
|**Скорость использования**: Аутентификация происходит одним нажатием кнопки, быстрее ввода кода.|**Ограниченная совместимость**: Некоторые смартфоны и планшеты могут не поддерживать определенные типы ключей, например, если нет нужных портов или программ на устройстве.|
|**Долговечность**: Некоторые модели могут служить годами без обслуживания.|**Необходимость обучения**: Для многих пользователей работа с физическим носителем менее понятна интуитивно, чем те же СМС.|

: Преимущества и недостатки аппаратных ключей безопасности {#tbl-pros-cons-keys}

# Биометрическая аутентификация

Отпечатки пальцев, сканирование лица, голосовая идентификация становятся все более распространенными способами двухфакторной аутентификации, особенно на мобильных устройствах. 

Пользователь заранее регистрирует себя в системе, после чего устройство (например, смартфон или специальный сканер) при каждом входе сверяет текущие биометрические данные с сохраненным шаблоном [@rtsolar2023].

|Плюсы|Минусы|
|-----|------|
|**Удобство использования**: Нет необходимости вводить коды или носить дополнительные устройства — аутентификация происходит за доли секунды.|**Проблемы с распознаванием**: Системы могут работать некорректно при изменениях внешности (борода, макияж, травмы), в условиях плохого освещения или при физических изменениях (порезы на пальцах).|
|**Сложно подделать**: Биометрические данные индивидуальны для каждого человека — это делает их надежным идентификатором. А современные биометрические системы трудно обмануть с помощью фотографий или записей.|**Вопросы приватности**: Сбор и хранение биометрических данных вызывает обеспокоенность из-за возможного неправомерного использования.|
|**Простота использования**: Пользователям не нужно запоминать дополнительную информацию или следовать инструкциям.|**Зависимость от оборудования**: Необходимы устройства со специальными датчиками, которые есть не во всех гаджетах.|

: Преимущества и недостатки биометрической аутентификации {#tbl-pros-cons-bio}

# Получение СМС-кодов

Когда большинство людей думают о двухфакторной аутентификации, они представляют именно СМС с кодом. Этот метод стал первым широко распространенным способом 2FA и до сих пор остается популярным. 

Чтобы подтвердить свою личность, пользователь вводит код, полученный в СМС, в специальное поле на сайте или в приложении [@unibell2024].

|Плюсы|Минусы|
|-----|------|
|**Доступность и простота использования**: Практически каждый человек имеет мобильный телефон, способный принимать СМС. Не нужно устанавливать дополнительные приложения или покупать специальные устройства.|**Уязвимость для перехвата**: СМС-сообщения не шифруются и их можно перехватить с помощью атак типа SIM-свопинг (подмена SIM-карты) или через уязвимости в протоколе SS7.|
|**Низкий порог входа**: Пользователи быстро понимают принцип: «получил сообщение — ввел код». Интуитивно понятно даже для тех, кто далек от технологий.|**Зависимость от сети**: Нет сигнала сотовой связи — нет доступа к аккаунту. Это создает проблемы в путешествиях или при нахождении в зонах с плохим покрытием сети.|
|**Широкая поддержка сервисами**: Большинство популярных платформ поддерживают СМС-аутентификацию, делая этот метод универсальным.|**Задержки в доставке кода**: СМС могут приходить с задержкой или не доставляться вовсе из-за перегрузки сетей.|

: Преимущества и недостатки СМС-кодов {#tbl-pros-cons-bio}

# Выводы

Независимо от выбранного метода, использование двухфакторной аутентификации значительно повышает безопасность аккаунтов по сравнению с защитой только паролем. Эксперты по информационной безопасности рекомендуют использовать комбинацию методов: основной способ (например, аутентификатор) и резервный (например, СМС) на случай потери доступа к основному.

# Список литературы{.unnumbered}

::: {#refs}
:::
